title: REXTECH Labs
description: Advanced security systems.
timezone: Etc/UTC

sass:
  style: compressed

defaults:
  - scope:
      path: assets/img
    values:
      image: true

exclude:
  - README.md
  - run.sh
  - update.sh

plugins:
  - jekyll-sitemap
  - jekyll-target-blank
